=== PoliTo-Rocket-Team/website-new/src/routes/(public)/apply/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "title": "List of positions",
    "description": "Details of each position",
    "type": "array",
    "items": {
        "type": "object",
        "title": "Position",
        "required": [
            "name",
            "subteam",
            "division",
            "code",
            "description",
            "desirable",
            "required",
            "form"
        ],
        "additionalProperties": false,
        "properties": {
            "name": {
                "type": "string"
            },
            "subteam": {
                "type": "string"
            },
            "division": {
                "type": "string"
            },
            "code": {
                "type": "string"
            },
            "description": {
                "oneOf": [
                    {
                        "type": "string",
                        "title": "Single paragraph"
                    },
                    {
                        "title": "Multiple paragraphs",
                        "type": "array",
                        "minItems": 1,
                        "items": {
                            "oneOf": [
                                {
                                    "title": "Paragraph",
                                    "type": "string"
                                },
                                {
                                    "title": "Bulletted list",
                                    "type": "array",
                                    "minItems": 1,
                                    "items": {
                                        "title": "Item",
                                        "type": "string"
                                    }
                                }
                            ]
                        }
                    }
                ]
            },
            "desirable": {
                "title": "Desirable skills/knowledge",
                "type": "array",
                "minLength": 1,
                "items": {
                    "type": "string"
                }
            },
            "required": {
                "title": "Required skills/knowledge",
                "oneOf": [
                    {
                        "title": "Nothing",
                        "type": "null"
                    },
                    {
                        "title": "List",
                        "type": "array",
                        "minLength": 1,
                        "items": {
                            "type": "string"
                        }
                    }
                ]
            },
            "form": {
                "type": "string",
                "title": "Form link",
                "description": "Url piece after 'https://forms.gle/', e.g. YkbJ4NzrXGN8r1xc9"
            }
        }
    }
}

=== PoliTo-Rocket-Team/website-new/src/routes/apply/data.json
[
    {
        "name": "Graphic Designer",
        "subteam": "Operations",
        "division": "Media",
        "code": "OPS-MDA-001",
        "description": "As a Graphic Designer, you will be in charge of designing the Team’s mission patches and logos, and help design the external coating of the Team’s rockets. You will design social media posts and website UI & UX in tight collaboration with photographers, video makers, rendering specialists, and web developers, leveraging modern design styles and patterns. ",
        "desirable": [
            "Attention to details and being up to date on the latest trends",
            "Experience in design motion graphics (charts, lower-thirds, GIFs, Animations, animated social media ads)",
            "Intermediate English writing skills"
        ],
        "required": [
            "Knowledge of prototyping softwares and graphics softwares",
            "Proficiency with Adobe Creative Suite Professional products,such as Illustrator, Photoshop, After Effects, Premiere, and InDesign, or similar",
            "Knowledge of Google Suite"
        ],
        "form": "kkNTvoskG8z2zY8cA"
    },
    {
        "name": "Social Media Manager",
        "subteam": "Operations",
        "division": "Media",
        "code": "OPS-MDA-002",
        "description": [
            "PoliTo Rocket Team is looking for one or more Social Media Manager(s), who will have the responsibility to maintain and enhance the team’s image by implementing social media platforms’ content strategies.",
            "This role will be required to run advertising campaigns and drive engagement by creating high-quality original content. The manager(s) should also oversee our community by managing interactions across all platforms."
        ],
        "desirable": [
            "Knowledge of the main social media platforms used by the Team (Instagram, LinkedIn, Twitter) and of additional social media platform to expand the Team's presence",
            "Attention to details and being up to date on the latest trends",
            "Previous experience in the media management and previous experience with paid content promotions",
            "Experience in design motion graphics (charts, lower-thirds, GIFs, Animations, animated social media ads)",
            "Proficiency with graphic design software such as Canva, Illustrator, Photoshop, After Effects, Premiere, and InDesign, or similar"
        ],
        "required": [
            "Professionalism and responsibility",
            "Intermediate/Advanced English writing skills",
            "Knowledge of Google Suite"
        ],
        "form": "kkNTvoskG8z2zY8cA"
    },
    {
        "name": "Video Maker",
        "subteam": "Operations",
        "division": "Media",
        "code": "OPS-MDA-003",
        "description": [
            "The Video Maker(s) will be responsible for designing, editing and producing video content for our earned media, website and social media channels. This position requires to remain flexible and adaptable, have strong planning skills and participate in many aspects of the Team’s daily work. The Video Maker will work in close collaboration with the Photographer(s) and Social Media Manager.",
            "It is very important to us to document every aspect of the Team’s operations. Hence, it will be needed to be present during the Team’s testing campaigns and launches, and take the best shots for the Team’s public appearance. It will be needed to film our members during their daily work and document the project's progress."
        ],
        "desirable": [
            "Experience in photography and photo editing",
            "Skilled at working and communicating with both technical and non-technical staff",
            "Attention to details and up to date on the latest trends",
            "Intermediate English writing skills"
        ],
        "required": [
            "Possession of an adequate camera",
            "Experience in Video Design or related field",
            "Proficiency with Adobe Creative Suite Professional products,such as Illustrator, Photoshop, After Effects, Premiere, and InDesign, or similar",
            "Knowledge of Google Suite"
        ],
        "form": "kkNTvoskG8z2zY8cA"
    },
    {
        "name": "Photographer",
        "subteam": "Operations",
        "division": "Media",
        "code": "OPS-MDA-004",
        "description": [
            "The Photographer(s) will be responsible for producing and editing photographic content for our earned media, website and social media channels. This position requires to remain flexible and adaptable, have strong planning skills and participate in many aspects of the Team’s daily work. The Photographer(s) will work in close collaboration with the Video Maker(s) and Social Media Manager.",
            "It is very important for the Team to document every public appearance. The Photographer(s) presence will be needed at every team event, mission and launch. The Photographer(s) will be asked to take the best shots during each event, in order to promote the image of the Team."
        ],
        "desirable": [
            "Proficiency with Adobe Creative Suite Professional products,such as Illustrator, Photoshop, After Effects, Premiere, and InDesign, or similar",
            "Skilled at working and communicating with both technical and non-technical staff",
            "Attention to details and up to date on the latest trends",
            "Intermediate English writing skills"
        ],
        "required": [
            "Experience in photography and photo editing",
            "Possession of an adequate camera",
            "Knowledge of Google Suite"
        ],
        "form": "kkNTvoskG8z2zY8cA"
    },
    {
        "name": "Web Developer",
        "subteam": "Operations",
        "division": "IT",
        "code": "OPS-ITC-001",
        "description": [
            "The role of the web developer is to manage the website in all its aspects, in order to present the team at its best. In particular, you will work with web technologies (SCSS, TypeScript, Svelte, Supabase) to design, create, and maintain all the website sections, based on the team directives.",
            "Mid term tasks could be:",
            [
                "Improve the projects page",
                "Create page transition effects",
                "Enhance the overall user experience and interactions with better animations and with 3D models"
            ],
            "A relatively big future project is the development of a backend that handles recruitment, renders pages based on information from (admin) lead engineers, and possibly receives and stores data collected during flights."
        ],
        "desirable": [
            "Knowledge of SCSS",
            "Knowledge of TypeScript",
            "Previous experience with Git and GitHub",
            "Previous experience with Svelte & SvelteKit",
            "Knowledge and previous use of the Three.js library",
            "Basic knowledge of Accessible Rich Internet Applications (ARIA)"
        ],
        "required": [
            "Proficiency in CSS",
            "Good knowledge of modern JavaScript (ECMAScript 2018)"
        ],
        "form": "arcXaamqyvxy4FYE7"
    },
    {
        "name": "Software Engineer",
        "subteam": "Vittorio Emanuele II",
        "division": "Mission Analysis",
        "code": "VES-MSA-001",
        "description": [
            "We're looking for software engineers to join our team. Your job would involve developing scripts for studying rocket trajectories and improving aerodynamics. Additionally, you'll create a virtual model to simulate rocket behavior in various scenarios. This will involve selecting appropriate physical models and parameters to represent the rocket's propulsion, aerodynamics, and control systems. Furthermore the created model must ensure that the simulation is accurate and that it can be used to analyze the rocket's performance.  The basic features of this model shall include:",
            [
                "6 degree of freedom flight simulation",
                "Realtime simulated altitude, velocity and acceleration display",
                "Aerodynamic models",
                "Solid motors models"
            ],
            "Future software features shall include:",
            [
                "Accurate weather modeling",
                "Automatic design optimization",
                "Parachutes with external trigger functions"
            ]
        ],
        "desirable": [
            "Knowledge of fluid dynamics and aerodynamics ",
            "Mastery of Matlab/Simulink",
            "Basic knowledge of CFD software",
            "Previous experience in GUI development"
        ],
        "required": [
            "Knowledge of a programming language suitable for performant scientific computing and numerical calculation, such as Python or Matlab/Simulink",
            "Knowledge of existing tools, libraries, or resources on flight simulation",
            "Collaboration with other developers",
            "Knowledge of Git and GitHub",
            "Basic knowledge of Latex"
        ],
        "form": "hj5QiiY8mqMFqtpQ8"
    },
    {
        "name": "Hardware Engineer",
        "subteam": "Vittorio Emanuele II",
        "division": "Avionics",
        "code": "VES-AVN-001",
